#!/bin/bash
# Video Explainer Skill - Installation Script

set -e

SKILL_NAME="video-explainer"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}Installing Video Explainer Skill for Claude Code${NC}"
echo ""

# Detect Claude Code directories
CLAUDE_SKILLS_DIR="${HOME}/.claude/skills"
CLAUDE_PLUGINS_DIR="${HOME}/.claude/plugins"
CONFIG_DIR="${HOME}/.config/video-explainer"

# Create directories if they don't exist
echo -e "${BLUE}Creating directories...${NC}"
mkdir -p "${CLAUDE_SKILLS_DIR}/${SKILL_NAME}"
mkdir -p "${CLAUDE_PLUGINS_DIR}/${SKILL_NAME}"
mkdir -p "${CONFIG_DIR}/brands"
mkdir -p "${CONFIG_DIR}/platforms"
mkdir -p "${CONFIG_DIR}/styles"
mkdir -p "${CONFIG_DIR}/skills/storytelling"
mkdir -p "${CONFIG_DIR}/skills/content-strategy"
mkdir -p "${CONFIG_DIR}/memory/production_history"
mkdir -p "${CONFIG_DIR}/memory/aggregated"

# Copy skill files
echo -e "${BLUE}Installing skill files...${NC}"
cp -r "${SCRIPT_DIR}/skill/"* "${CLAUDE_SKILLS_DIR}/${SKILL_NAME}/"

# Build and copy plugin
echo -e "${BLUE}Building plugin...${NC}"
if [ -f "${SCRIPT_DIR}/plugin/package.json" ]; then
    cd "${SCRIPT_DIR}/plugin"
    npm install --quiet 2>/dev/null || echo -e "${YELLOW}npm install skipped (may need manual setup)${NC}"
    npm run build --quiet 2>/dev/null || echo -e "${YELLOW}Build skipped (may need manual setup)${NC}"
    cd "${SCRIPT_DIR}"
fi

# Copy plugin (dist or src as fallback)
if [ -d "${SCRIPT_DIR}/plugin/dist" ]; then
    cp -r "${SCRIPT_DIR}/plugin/dist/"* "${CLAUDE_PLUGINS_DIR}/${SKILL_NAME}/" 2>/dev/null || true
fi
cp "${SCRIPT_DIR}/plugin/package.json" "${CLAUDE_PLUGINS_DIR}/${SKILL_NAME}/" 2>/dev/null || true

# Copy default configs (only if user configs don't exist)
echo -e "${BLUE}Setting up default configurations...${NC}"
if [ ! -f "${CONFIG_DIR}/config.yaml" ]; then
    cat > "${CONFIG_DIR}/config.yaml" << 'EOF'
# Video Explainer Configuration
# Generated by install.sh

# Path to video_explainer CLI (set via /video setup)
video_explainer_path: null

# Default settings
defaults:
  brand: null
  style: minimal
  voice_provider: elevenlabs

# Learning settings
learning:
  enabled: true
  auto_capture: true
EOF
fi

# Copy default brand/platform/style definitions
for category in brands platforms styles; do
    if [ -f "${SCRIPT_DIR}/defaults/${category}/_defaults.yaml" ]; then
        cp "${SCRIPT_DIR}/defaults/${category}/_defaults.yaml" "${CONFIG_DIR}/${category}/" 2>/dev/null || true
    fi
done

# Copy technique skills
if [ -d "${SCRIPT_DIR}/defaults/techniques" ]; then
    cp -r "${SCRIPT_DIR}/defaults/techniques/"* "${CONFIG_DIR}/skills/" 2>/dev/null || true
fi

echo ""
echo -e "${GREEN}Installation complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Run '/video setup' to configure the video_explainer path"
echo "  2. Run '/video brands create' to create your first brand"
echo "  3. Run '/video new my-project' to start creating videos"
echo ""
echo "Installed to:"
echo "  Skill:   ${CLAUDE_SKILLS_DIR}/${SKILL_NAME}/"
echo "  Plugin:  ${CLAUDE_PLUGINS_DIR}/${SKILL_NAME}/"
echo "  Config:  ${CONFIG_DIR}/"
